window.define("ClientSideMetrics",["JSONUtils","ClientSideUtils","EventUtils",window,document],function(q,n,r,m,l){function p(f,a,e,g,b,s){return f+"/event/"+a+"?"+("arid\x3d"+e+"\x26abid\x3d"+g+(s?"\x26testing\x3dtrue":""))+"\x26ev\x3d"+encodeURIComponent(q.from(b))}function k(f,a,e,g,b){b={tags:b||"fallback",type:"error",clientEventTime:(new Date).getTime()};f&&(b.message="[object Error]"===Object.prototype.toString.apply(f)?f.message:f);a&&(b.url=a);e&&(b.lineNumber=e);g&&(b.columnNumber=g);return b}
function t(){var a={},h=l.documentElement,e=l.getElementsByTagName("body")[0];a.viewportSize=(window.innerWidth||h.clientWidth||e.clientWidth)+"x"+(window.innerHeight||h.clientHeight||e.clientHeight);window.performance&&window.performance.timing?(a.navigationStartTime=window.performance.timing.navigationStart,a.clientStartTime=window.performance.timing.domLoading,a.clientEndTime=window.performance.timing.domComplete):(a.clientStartTime=u,a.clientEndTime=(new Date).getTime());window.performance&&window.performance.navigation&&
(a.navigationType=window.performance.navigation.type,a.navigationRedirectCount=window.performance.navigation.redirectCount);h=window.registerFallbackHandler||function(){};try{window.location&&(a.clientProtocol=window.location.protocol)}catch(g){h("cse",k("Failed window.location: "+g,void 0,void 0,void 0,"ignored"))}try{window.parent&&window.parent===window&&(a.adNotInIframe=!0)}catch(b){h("cse",k("Failed window.parent: "+b,void 0,void 0,void 0,"ignored"))}window.JSON&&window.JSON.stringify||(a.noNativeJson=
!0);"string"===typeof l.compatMode&&(a.inQuirksMode="CSS1Compat"!==l.compatMode);return a}var u=(new Date).getTime(),a=n.Metric,v=r.getClickXY,w=new n.PixelQueue;return{init:function(f,h,e,g){var b=function(){return function(a,b){var c=new Image;c.src=p(f,a,h,e,b,g);c.style.display="none";c.width=c.height=1;w.addPixel(c)}}();window.registerFallbackHandler&&window.registerFallbackHandler(function(a,d,c,e,f){b("cse",k(a,d,c,e,f))});new a({start:"load",limit:1,element:window,after:function(){b("csm",
t())}});new a({start:"load",limit:1,element:window,after:function(){if(window.performance&&window.performance.timing)var a=setInterval(function(){0!==window.performance.timing.loadEventEnd&&(clearInterval(a),b("csi",{type:"performanceTiming",performanceTiming:window.performance.timing}))},50)}});new a({start:"mouseover",limit:1,after:function(a){b("csi",{type:"touch",touchStart:a})}});new a({start:"mouseover",end:"mouseout",limit:1,a:500,after:function(a,d){b("csi",{type:"hover",hoverStart:a,hoverDuration:d})}});
new a({start:"play",end:["pause","ended"],limit:1,a:0,after:function(a,d){b("csi",{type:"play",playStart:a,playTime:d})}});new a({start:"dra-video-playallowed",custom:!0,limit:1,after:function(){b("csi",{type:"dra-video-playallowed"})}});new a({start:"dra-video-playblocked",custom:!0,limit:1,after:function(){b("csi",{type:"dra-video-playblocked"})}});new a({start:"dra-visible",custom:!0,limit:1,after:function(a,d,c){0<c&&b("csi",{type:"dra-hidden-ad-rendered",hiddenTimeMs:c})}});new a({start:"dra-visibility-polling-timeout",
custom:!0,limit:1,after:function(a,d,c){b("csi",{type:"dra-hidden-ad-timeout",hiddenTimeMs:c})}});new a({start:"dra-landscape",custom:!0,limit:1,after:function(){b("csi",{type:"landscape",landscape:!0})}});new a({start:"dra-portrait",custom:!0,limit:1,after:function(){b("csi",{type:"landscape",landscape:!1})}});new a({start:"click",after:function(a,d,c){a=v(c);d=l.getElementById("dra-body");b("csi",{type:"click",clickX:a.pageX,clickY:a.pageY,bodySize:d?d.offsetWidth+"x"+d.offsetHeight:void 0})}});
new a({start:"simulate-click-unsupported",custom:!0,limit:1,after:function(a,d,c){b("csi",{type:"simulate-click-unsupported",useragent:c&&"string"===typeof c[0]?c[0].substring(0,512):"NONE"})}});new a({start:"dra-osdetect-error",custom:!0,limit:1,after:function(a,d,c){b("cse",k(c?"MoPub userAgent mismatch: Provided: "+c[0]+"; Actual: "+c[1]+"; Raw User Agent: "+(m.navigator&&m.navigator.userAgent?m.navigator.userAgent.substring(0,512):"NONE"):"MoPub userAgent mismatch",void 0,void 0,void 0,"dra-osdetect-error"))}});
new a({start:"dra-nexage-openinbrowser-timeout",custom:!0,limit:1,after:function(){b("cse",k("Nexage SDK openInBrowser timeout",void 0,void 0,void 0,"dra-nexage-openinbrowser-timeout"))}});new a({start:"dra-aman-msdkbridge-error",custom:!0,limit:1,after:function(a,d,c){b("cse",k(c.amazon?"amazon.openInExternalBrowser \x3d "+typeof c.amazon.openInExternalBrowser:"amazon bridge missing",void 0,void 0,void 0,"dra-aman-msdkbridge-error"))}});new a({start:"pretrashed",limit:1,custom:!0,after:function(){b("csi",
{type:"pretrashed"})}});new a({start:"trashed",limit:10,custom:!0,after:function(){b("csi",{type:"trashed"})}});new a({start:"restored",limit:10,custom:!0,after:function(){b("csi",{type:"restored"})}})},formatPetsEvent:p}});