$(function(){var a=$(".col-md-2 .sidebar");320>=window.innerWidth&&($("body").css("fontSize","95%"),$("button").css("fontSize","85%"));/iPhone|iPod|iPad/i.test(navigator.userAgent)&&$(".btn-quick-guide").css("display","none");$("#pull").unbind("click").on("click",function(c){c.preventDefault();c.stopPropagation();window.scrollTo(0,0);a.toggle("slide")})});
$(function(){$(".header-search-box").click(function(a){a.stopPropagation()});$(".magnifying-glass").click(function(a){$(".header-search-box").is(":hidden")?(a.stopPropagation(),$(".header-search-box").show().focus(),$(".header-search-box").animate({width:100==$(".header-search-box").width()?"0px":"435px",opacity:1},"slow",function(){0==$(".header-search-box").width()&&$(".header-search-box").hide()})):$el.animate({width:435==$el.width()?"435px":"0px",opacity:.3},"slow",function(){0==$el.width()&&
$el.hide()})})});$(document).on("click",function(a){var c=$(".header-search-box");c.is(":visible")&&c.animate({width:435==c.width()?"435px":"0px",opacity:.3},"slow",function(){0==c.width()&&c.hide()})});
(function(a){a.extend({scrollToTop:function(){var c=!1;a("body").append(a("<a />").addClass("scroll-to-top").attr({href:"#",id:"scrollToTop"}).append(a("<i />").addClass("icon icon-chevron-up icon-white")));a("#scrollToTop").click(function(c){c.preventDefault();a("body, html").animate({scrollTop:0},500);return!1});a(window).scroll(function(){var b=a(window).scrollTop();35>b?a("#pull").attr("style","top: 24px!important"):35<b&&(b-=10,a("#pull").attr("style","top: "+b+"px!important"));c||(c=!0,150<
a(window).scrollTop()?a("#scrollToTop").stop(!0,!0).addClass("visible"):a("#scrollToTop").stop(!0,!0).removeClass("visible"),c=!1)})}})})(jQuery);
(function(a){var c={action:function(){},runOnLoad:!1,duration:500},b=!1,e,d={init:function(){for(var b=0;b<=arguments.length;b++){var e=arguments[b];switch(typeof e){case "function":c.action=e;break;case "boolean":c.runOnLoad=e;break;case "number":c.duration=e}}return this.each(function(){c.runOnLoad&&c.action();a(this).resize(function(){d.timedAction.call(this)})})},timedAction:function(a,d){var l=function(){var a=c.duration;if(b&&(a=c.duration-(new Date-e),0>=a)){clearTimeout(b);b=!1;c.action();
return}b=setTimeout(l,a)};e=new Date;"number"===typeof d&&(c.duration=d);"function"===typeof a&&(c.action=a);b||l()}};a.fn.afterResize=function(a){return d[a]?d[a].apply(this,Array.prototype.slice.call(arguments,1)):d.init.apply(this,arguments)}})(jQuery);
(function(){var a={initialized:!1,initialize:function(){this.initialized||(this.initialized=!0,this.build(),this.events())},build:function(){$.scrollToTop();this.featuredBoxes();this.toggle()},events:function(){$(window).afterResize(function(){a.featuredBoxes()})},featuredBoxes:function(){$("div.featured-box").css("height","auto");$("div.featured-boxes").each(function(){var a=$(this),b=0;$("div.featured-box",a).each(function(){$(this).height()>b&&(b=$(this).height())});$("div.featured-box",a).height(b)})},
toggle:function(){$("section.toggle > label").prepend($("<i />").addClass("icon icon-plus"));$("section.toggle > label").prepend($("<i />").addClass("icon icon-minus"));$("section.toggle.active > p").addClass("preview-active");$("section.toggle.active > div.toggle-content").slideDown(350,function(){});$("section.toggle > label").click(function(a){var b=$(this).parent(),e=$(this).parents("div.toogle"),d=!1;e.hasClass("toogle-accordion")&&"undefined"!=typeof a.originalEvent&&e.find("section.toggle.active > label").trigger("click");
b.toggleClass("active");if(b.find("> p").get(0)){d=b.find("> p");a=d.css("height");d.css("height","auto");var h=d.css("height");d.css("height",a)}a=b.find("> div.toggle-content");b.hasClass("active")?($(d).animate({height:h},350,function(){$(this).addClass("preview-active")}),a.slideDown(350,function(){})):($(d).animate({height:25},350,function(){$(this).removeClass("preview-active")}),a.slideUp(350,function(){}))})}};a.initialize()})();
(function(a){a.TryIt=function(c,b){var e={url:c},d=this;d.settings={};d.compile=function(){a(".prettyprint.tryit").click(function(c){var b=a(this).text(),e="",g="",h="",m="",k="";if(a(this).attr("title")){var f=a(this).attr("title").split(",");f[0]&&(e=a("#"+f[0].trim()+"").text());f[1]&&(g=a("#"+f[1].trim()+"").text());f[2]&&(k=f[2],h=a("#"+f[2].trim()+"").text());f[3]&&(k=f[3],m=a("#"+f[3].trim()+"").text())}a("#source").text(b);a("#supportsource").text(e);a("#utilsource").text(g);a("#extrasource").text(h);
a("#inputs").text(m);a("#filename").text(k);b=a(this).width()+12;a(this).height();e=a(this).offset().left;g=a(this).offset().top;e=Math.round(e);e=c.pageX-e;X=b-e;g=Math.round(g);g=c.pageY-g;36>=X&&36>=g&&(c.preventDefault(),768>=window.innerWidth?a.colorbox({iframe:!0,reposition:!0,opacity:.35,href:d.settings.url,width:window.innerWidth,height:window.innerHeight}):(a(window).height(),a.colorbox({iframe:!0,reposition:!0,opacity:.35,href:d.settings.url,width:960,height:650})))})};var h=a(window).innerWidth()/
2-320;a(".inline").colorbox({inline:!0,left:h,width:"615px",opacity:.5});(function(){d.settings=a.extend({},e,b);a("body").append('<div id="source" style="display:none;"></div>');a("body").append('<div id="supportsource" style="display:none;"></div>');a("body").append('<div id="utilsource" style="display:none;"></div>');a("body").append('<div id="extrasource" style="display:none;"></div>');a("body").append('<div id="inputs" style="display:none;"></div>');a("body").append('<div id="filename" style="display:none;"></div>');
a(".prettyprint.tryit").mousemove(function(e){var c=a(this).width()+12;a(this).height();var b=a(this).offset().left,d=a(this).offset().top,b=Math.round(b),b=e.pageX-b;X=c-b;d=Math.round(d);d=e.pageY-d;36>=X&&36>=d?a(this).css("cursor","pointer"):a(this).css("cursor","default")})})()}})(jQuery);
$(document).ready(function(){var a=location.href;filename=a.substring(a.lastIndexOf(".com")+5);-1==filename.lastIndexOf(".htm")&&(filename+="index.htm");0==$('.sidebar li a[href*= "'+filename+'"]').text().length&&(filename=$(".parent-file").text());if(-1==filename.lastIndexOf("whoiswho")){$('ul.nav-list.primary>li a[href*= "'+filename+'"]').css("color","");$('ul.nav-list.primary>li a[href*= "'+filename+'"]').css("background-color","#d6d6d6");$('ul.submenu>li a[href*= "'+filename+'"]').css("color",
"");$('ul.submenu>li a[href*= "'+filename+'"]').css("background-color","#d6d6d6!important");var c=!1,b=!1;$(document).on("click",".cclose",function(a){$(".submenu-item").hide()});$("#liTL").click(function(a){a.stopPropagation();$.ajax({url:"tutorials-submenu.htm"}).done(function(a){$("#top-sub-menu").html(a);c?($(".submenu-item").hide(),c=!1):($(".submenu-item").show(),c=!0,b=!1)})});$("#liCG").click(function(a){a.stopPropagation();$.ajax({url:"codingground-submenu.htm"}).done(function(a){$("#top-sub-menu").html(a);
b?($(".submenu-item").hide(),b=!1):($(".submenu-item").show(),b=!0,c=!1)})});$(document).on("click",function(a){a=$(".submenu-item");a.is(":visible")&&a.hide()});$(".no-sub-menu").on("click",function(a){a=$(".submenu-item");a.is(":visible")&&a.hide()});$("#btnemail").on("click",function(a){a={email:$("#textemail").val()};$("#newsresponse").css({display:"block"});if(!/^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/.test($("#textemail").val()))return $("#newsresponse").html("Please enter a valid email id"),
$("#newsresponse").fadeOut(5E3,function(){$("#newsresponse").html("");$("#textemail").val("")}),!1;$.ajax({type:"POST",url:"/subs-news.php",data:a,dataType:"json",beforeSend:function(){$(".wrapLoader").css({display:"block"})},success:function(a){$(".wrapLoader").css({display:"none"});0<a.ret?$("#newsresponse").html("You already have a subscription"):$("#newsresponse").html("Thanks for your subscription");$("#newsresponse").fadeOut(5E3,function(){$("#newsresponse").html("");$("#textemail").val("")})}})});
$("form button.btn").on("click",function(){$(this).find("a").attr("href")&&(window.location.href=$(this).find("a").attr("href"))})}});$(window).load(function(){$(".middle-col").height()<$(".sidebar").height()&&991<window.innerWidth&&$(".middle-col").css("height",$(".sidebar").height()+50);$(".middle-col").height()<$("#rightbar").height()&&991<window.innerWidth&&$(".middle-col").css("height","1171");/iPhone|iPad|iPod/i.test(navigator.userAgent)&&($(".android").hide(),$(".microsoft").hide(),$(".hide-me").hide())});
function resizeFrame(a){a.height="200px";a.height=a.contentWindow.document.body.scrollHeight+5+"px"}468>window.innerWidth&&($(".topgooglead").html(""),$(".topgooglead").html('<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js">\x3c/script><ins class="adsbygoogle"     style="display:inline-block;width:300px;height:250px"     data-ad-client="ca-pub-7133395778201029"    data-ad-slot="8354544120"></ins><script>(adsbygoogle = window.adsbygoogle || []).push({});\x3c/script>'));