var _yt_www={};(function(g){var window=this;var baa,caa,Aa,Za,$a,kaa,eb,fb,laa,nb,maa,ub,Gb,Wb,bc,dc,Hc,xaa,yaa,waa,pd,zaa,zd,Cd,Bd,Ad,Caa,Daa,Eaa,Faa,Jd,Ld,Md,Od,Qd,Haa,Ud,Gd,Rd,Td,Dd,Id,Nd,Kd,Vd,Jaa,he,ke,ne,pe,xe,ye,Se,Te,Oaa,af,bf,Paa,ef,jf,gf,ff,Qaa,mf,nf,qf,sf,tf,uf,xf,Af,zf,wf,yf,Bf,of,rf,Waa,Cf,Df,Xaa,Yaa,Jf,Lf,Nf,Rf,Qf,Sf,Uf,Zaa,$aa,aba,Zf,cg,dg,eg,hg,ig,jg,gba,hba,$f,bg,Yf,fba,ag,mg,ng,pa,aaa;g.ba=function(a){return function(){return g.aa[a].apply(this,arguments)}};
g.ca=function(a){return void 0!==a};
g.l=function(a,b,c){a=a.split(".");c=c||g.da;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&g.ca(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};
g.m=function(a,b){for(var c=a.split("."),d=b||g.da,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};
g.ea=function(){};
g.fa=function(a){a.getInstance=function(){return a.Cc?a.Cc:a.Cc=new a}};
g.ga=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};
g.ha=function(a){return"array"==g.ga(a)};
g.ia=function(a){var b=g.ga(a);return"array"==b||"object"==b&&"number"==typeof a.length};
g.la=function(a){return"string"==typeof a};
g.ma=function(a){return"number"==typeof a};
g.na=function(a){return"function"==g.ga(a)};
g.oa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};
g.qa=function(a){return a[pa]||(a[pa]=++aaa)};
baa=function(a,b,c){return a.call.apply(a.bind,arguments)};
caa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};
g.p=function(a,b,c){g.p=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?baa:caa;return g.p.apply(null,arguments)};
g.ra=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};
g.q=function(a,b){function c(){}
c.prototype=b.prototype;a.N=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,h){for(var k=Array(arguments.length-2),n=2;n<arguments.length;n++)k[n-2]=arguments[n];return b.prototype[c].apply(a,k)}};
g.sa=function(a){g.sa[" "](a);return a};
g.ta=function(a,b){return 0==a.lastIndexOf(b,0)};
g.va=function(a){return(0,window.encodeURIComponent)(String(a))};
g.wa=function(a){if(!daa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(eaa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(faa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gaa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(haa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(iaa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jaa,"&#0;"));return a};
g.xa=function(a,b){return-1!=a.indexOf(b)};
g.ya=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
g.Ba=function(a,b){for(var c=0,d=(0,g.za)(String(a)).split("."),e=(0,g.za)(String(b)).split("."),h=Math.max(d.length,e.length),k=0;0==c&&k<h;k++){var n=d[k]||"",r=e[k]||"",B=RegExp("(\\d*)(\\D*)","g"),D=RegExp("(\\d*)(\\D*)","g");do{var N=B.exec(n)||["","",""],Y=D.exec(r)||["","",""];if(0==N[0].length&&0==Y[0].length)break;c=Aa(0==N[1].length?0:(0,window.parseInt)(N[1],10),0==Y[1].length?0:(0,window.parseInt)(Y[1],10))||Aa(0==N[2].length,0==Y[2].length)||Aa(N[2],Y[2])}while(0==c)}return c};
Aa=function(a,b){return a<b?-1:a>b?1:0};
g.Ca=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c)>>>0;return b};
g.Da=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};
g.Ea=function(a){var b=g.la(void 0)?g.ya(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};
g.Ha=function(a,b,c){b=g.Fa(a,b,c);return 0>b?null:g.la(a)?a.charAt(b):a[b]};
g.Fa=function(a,b,c){for(var d=a.length,e=g.la(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&b.call(c,e[h],h,a))return h;return-1};
g.Ja=function(a,b){return 0<=(0,g.Ia)(a,b)};
g.La=function(a,b){var c=(0,g.Ia)(a,b),d;(d=0<=c)&&g.Ka(a,c);return d};
g.Ka=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};
g.Ma=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
g.Na=function(a){return function(){return a}};
g.Oa=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};
g.Pa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};
g.Qa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
g.Ra=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};
g.Sa=function(a,b){b in a&&delete a[b]};
g.Ta=function(a,b,c){if(null!==a&&b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};
g.Ua=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
g.Wa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var h=0;h<Va.length;h++)c=Va[h],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
g.Ya=function(a){return g.xa(g.Xa,a)};
Za=function(){return g.Ya("Opera")||g.Ya("OPR")};
$a=function(){return(g.Ya("Chrome")||g.Ya("CriOS"))&&!Za()&&!g.Ya("Edge")};
g.bb=function(a){g.da.setTimeout(function(){throw a;},0)};
kaa=function(){var a=g.da.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!g.Ya("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,g.p)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);
b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});
if("undefined"!==typeof a&&!g.Ya("Trident")&&!g.Ya("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(g.ca(c.next)){c=c.next;var a=c.Pp;c.Pp=null;a()}};
return function(a){d.next={Pp:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};
window.document.documentElement.appendChild(b)}:function(a){g.da.setTimeout(a,0)}};
g.cb=function(a,b,c){this.F=c;this.B=a;this.D=b;this.C=0;this.A=null};
g.db=function(a,b){a.D(b);a.C<a.F&&(a.C++,b.next=a.A,a.A=b)};
eb=function(){this.C=this.A=null};
fb=function(){this.next=this.scope=this.Ee=null};
g.lb=function(a,b){gb||laa();ib||(gb(),ib=!0);var c=jb,d=kb.get();d.set(a,b);c.C?c.C.next=d:c.A=d;c.C=d};
laa=function(){if(g.da.Promise&&g.da.Promise.resolve){var a=g.da.Promise.resolve(void 0);gb=function(){a.then(nb)}}else gb=function(){var a=nb;
!g.na(g.da.setImmediate)||g.da.Window&&g.da.Window.prototype&&!g.Ya("Edge")&&g.da.Window.prototype.setImmediate==g.da.setImmediate?(ob||(ob=kaa()),ob(a)):g.da.setImmediate(a)}};
nb=function(){for(var a=null;a=jb.remove();){try{a.Ee.call(a.scope)}catch(b){g.bb(b)}g.db(kb,a)}ib=!1};
g.pb=function(){this.Gd=this.Gd;this.Ib=this.Ib};
g.sb=function(a,b){g.qb(a,g.ra(g.rb,b))};
g.qb=function(a,b){a.Gd?b.call(void 0):(a.Ib||(a.Ib=[]),a.Ib.push(g.ca(void 0)?(0,g.p)(b,void 0):b))};
g.rb=function(a){a&&"function"==typeof a.dispose&&a.dispose()};
g.tb=function(a){g.pb.call(this);this.D=1;this.C=[];this.B=0;this.A=[];this.Ed={};this.F=!!a};
maa=function(a,b,c){g.lb(function(){a.apply(b,c)})};
g.wb=function(a){ub(g.vb,arguments)};
g.t=function(a,b){return a in g.vb?g.vb[a]:b};
g.yb=function(a,b){g.na(a)&&(a=g.xb(a));return window.setTimeout(a,b)};
g.zb=function(a,b){g.na(a)&&(a=g.xb(a));return window.setInterval(a,b)};
g.Ab=function(a){window.clearTimeout(a)};
g.Bb=function(a){window.clearInterval(a)};
g.xb=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw g.Cb(b),b;}}:a};
g.Cb=function(a,b){var c=g.m("yt.logging.errors.log");c?c(a,b,void 0,void 0):(c=g.t("ERRORS",[]),c.push([a,b,void 0,void 0]),g.wb("ERRORS",c))};
g.Eb=function(a){return a in g.Db};
g.Fb=function(a,b,c){var d=b||{};if(a=a in g.Db?g.Db[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});
return a};
ub=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
g.Lb=function(a,b,c){var d=Gb();if(d){var e=d.subscribe(a,function(){if(!Hb||Hb!=e){var d=arguments,k=function(){Ib[e]&&b.apply(c||window,d)};
try{Jb[a]?k():g.yb(k,0)}catch(n){g.Cb(n)}}},c);
Ib[e]=!0;Kb[a]||(Kb[a]=[]);Kb[a].push(e);return e}return 0};
g.Mb=function(a){var b=Gb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,g.u)(a,function(a){b.unsubscribeByKey(a);delete Ib[a]}))};
g.v=function(a,b){var c=Gb();return c?c.publish.apply(c,arguments):!1};
g.Nb=function(a,b){Jb[a]=!0;var c=Gb(),c=c?c.publish.apply(c,arguments):!1;Jb[a]=!1;return c};
Gb=function(){return g.m("yt.pubsub.instance_")};
g.Ob=function(){return!!g.m("yt.scheduler.instance")};
g.Pb=function(a,b){(0,window.isNaN)(b)&&(b=void 0);var c=g.m("yt.scheduler.instance.addJob");return c?c(a,0,b):void 0===b?(a(),window.NaN):g.yb(a,b||0)};
g.Qb=function(a,b){return g.Pb(a,b)};
g.Rb=function(a){if(!(0,window.isNaN)(a)){var b=g.m("yt.scheduler.instance.cancelJob");b?b(a):g.Ab(a)}};
g.Sb=function(a){for(var b=0,c=a.length;b<c;b++)g.Rb(a[b])};
g.Tb=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.G=d?g.xb(d):null;this.F=e?g.xb(e):null;this.D=[];this.A=this.C=0};
g.Ub=function(a){g.Rb(a.C);a.C=g.Qb((0,g.p)(a.init,a))};
g.Xb=function(a){a.name in Vb&&Wb(a.name);Vb[a.name]={reqs:[],disable:(0,g.p)(a.disable,a)};(0,g.u)(a.deps,function(b){if(!(b in Vb))throw Error("Module "+b+" required by "+a.name);Vb[b].reqs.push(a.name)});
a.enable()};
Wb=function(a){if(a in Vb){var b=Vb[a];(0,g.u)(b.reqs,function(a){Wb(a)});
try{b.disable()}catch(c){}delete Vb[a]}};
g.Zb=function(){this.A="";this.C=Yb};
g.$b=function(a){return a instanceof g.Zb&&a.constructor===g.Zb&&a.C===Yb?a.A:"type_error:Const"};
bc=function(){this.A="";this.C=ac};
g.cc=function(a){if(a instanceof bc&&a.constructor===bc&&a.C===ac)return a.A;g.ga(a);return"type_error:SafeStyle"};
dc=function(a){var b=new bc;b.A=a;return b};
g.ec=function(a){var b="",c;for(c in a){if(!/^[-_a-zA-Z0-9]+$/.test(c))throw Error("Name allows only [-_a-zA-Z0-9], got: "+c);var d=a[c];if(null!=d){if(d instanceof g.Zb)d=g.$b(d);else if(naa.test(d)){for(var e=!0,h=!0,k=0;k<d.length;k++){var n=d.charAt(k);"'"==n&&h?e=!e:'"'==n&&e&&(h=!h)}e&&h||(d="zClosurez")}else d="zClosurez";b+=c+":"+d+";"}}return b?dc(b):oaa};
g.gc=function(){this.A="";this.C=fc};
g.hc=function(a){if(a instanceof g.gc&&a.constructor===g.gc&&a.C===fc)return a.A;g.ga(a);return"type_error:SafeUrl"};
g.jc=function(a){if(a instanceof g.gc)return a;a=a.Yf?a.$e():String(a);paa.test(a)||(a="about:invalid#zClosurez");return g.ic(a)};
g.ic=function(a){var b=new g.gc;b.A=a;return b};
g.lc=function(){this.A="";this.C=kc};
g.mc=function(a){if(a instanceof g.lc&&a.constructor===g.lc&&a.C===kc)return a.A;g.ga(a);return"type_error:TrustedResourceUrl"};
g.oc=function(){this.A="";this.B=nc;this.C=null};
g.pc=function(a){if(a instanceof g.oc&&a.constructor===g.oc&&a.B===nc)return a.A;g.ga(a);return"type_error:SafeHtml"};
g.rc=function(a){if(a instanceof g.oc)return a;var b=null;a.Om&&(b=a.Gg());a=g.wa(a.Yf?a.$e():String(a));return g.qc(a,b)};
g.uc=function(a,b,c){if(!sc.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toUpperCase()in qaa)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");return g.tc(a,b,c)};
g.vc=function(a){function b(a){g.ha(a)?(0,g.u)(a,b):(a=g.rc(a),d+=g.pc(a),a=a.Gg(),0==c?c=a:0!=a&&c!=a&&(c=null))}
var c=0,d="";(0,g.u)(arguments,b);return g.qc(d,c)};
g.qc=function(a,b){var c=new g.oc;c.A=a;c.C=b;return c};
g.tc=function(a,b,c){var d=null,e="<"+a;if(b)for(var h in b){if(!sc.test(h))throw Error('Invalid attribute name "'+h+'".');var k=b[h];if(null!=k){var n,r=a;n=h;if(k instanceof g.Zb)k=g.$b(k);else if("style"==n.toLowerCase()){if(!g.oa(k))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof k+" given: "+k);k instanceof bc||(k=g.ec(k));k=g.cc(k)}else{if(/^on/i.test(n))throw Error('Attribute "'+n+'" requires goog.string.Const value, "'+k+'" given.');if(n.toLowerCase()in
raa)if(k instanceof g.lc)k=g.mc(k);else if(k instanceof g.gc)k=g.hc(k);else if(g.la(k))k=g.jc(k).$e();else throw Error('Attribute "'+n+'" on tag "'+r+'" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+k+'" given.');}k.Yf&&(k=k.$e());n=n+'="'+g.wa(String(k))+'"';e=e+(" "+n)}}null!=c?g.ha(c)||(c=[c]):c=[];!0===saa[a.toLowerCase()]?e+=">":(d=g.vc(c),e+=">"+g.pc(d)+"</"+a+">",d=d.Gg());(a=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(a)?d=0:d=null);return g.qc(e,d)};
g.wc=function(a,b){a.innerHTML=g.pc(b)};
g.xc=function(a,b){var c;c=b instanceof g.gc?b:g.jc(b);a.href=g.hc(c)};
g.w=function(a,b){return a?a.dataset?a.dataset[g.yc(b)]:a.getAttribute("data-"+b):null};
g.zc=function(a,b){return a?a.dataset?g.yc(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};
g.yc=function(a){return Ac[a]||(Ac[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};
g.Cc=function(a,b){var c=g.Bc(a);window.spf.script.load(a,c,b)};
g.Dc=function(a,b){var c=g.Bc(a);window.spf.script.ignore(c,b)};
g.Bc=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(taa,""),b=b.replace(uaa,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};
g.Ec=function(a,b){this.x=g.ca(a)?a:0;this.y=g.ca(b)?b:0};
g.Fc=function(a,b){this.width=a;this.height=b};
g.Gc=function(){return g.Ya("iPhone")&&!g.Ya("iPod")&&!g.Ya("iPad")};
Hc=function(){var a=g.da.document;return a?a.documentMode:void 0};
g.Kc=function(a){return Ic[a]||(Ic[a]=0<=g.Ba(g.Jc,a))};
g.Mc=function(a){return Number(g.Lc)>=a};
g.x=function(a){return g.la(a)?window.document.getElementById(a):a};
g.Nc=function(a){return g.la(a)?window.document.getElementById(a):a};
g.y=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=g.Oc(window.document,"*",a,b)[0];return d||null};
g.Oc=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,h=0,k;k=a[h];h++)b==k.nodeName&&(d[e++]=k);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(h=e=0;k=a[h];h++)b=k.className,"function"==typeof b.split&&g.Ja(b.split(/\s+/),c)&&(d[e++]=k);d.length=e;return d}return a};
g.Qc=function(a,b){g.Pa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Pc.hasOwnProperty(d)?a.setAttribute(Pc[d],b):g.ta(d,"aria-")||g.ta(d,"data-")?a.setAttribute(d,b):a[d]=b})};
g.Sc=function(a){return g.Rc(a||window)};
g.Rc=function(a){a=a.document;a=g.Tc(a)?a.documentElement:a.body;return new g.Fc(a.clientWidth,a.clientHeight)};
g.Vc=function(a){var b=g.Uc(a);a=a.parentWindow||a.defaultView;return g.z&&g.Kc("10")&&a.pageYOffset!=b.scrollTop?new g.Ec(b.scrollLeft,b.scrollTop):new g.Ec(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
g.Uc=function(a){return a.scrollingElement?a.scrollingElement:!g.Wc&&g.Tc(a)?a.documentElement:a.body||a.documentElement};
g.Zc=function(a,b,c){return g.Xc(window.document,arguments)};
g.Xc=function(a,b){var c=b[0],d=b[1];if(!vaa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',g.wa(d.name),'"');if(d.type){c.push(' type="',g.wa(d.type),'"');var e={};g.Wa(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(g.la(d)?c.className=d:g.ha(d)?c.className=d.join(" "):g.Qc(c,d));2<b.length&&g.$c(a,c,b,2);return c};
g.$c=function(a,b,c,d){function e(c){c&&b.appendChild(g.la(c)?a.createTextNode(c):c)}
for(;d<c.length;d++){var h=c[d];!g.ia(h)||g.oa(h)&&0<h.nodeType?e(h):(0,g.u)(waa(h)?g.Ma(h):h,e)}};
g.Tc=function(a){return"CSS1Compat"==a.compatMode};
g.ad=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};
g.bd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};
g.cd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
xaa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
yaa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
g.dd=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
waa=function(a){if(a&&"number"==typeof a.length){if(g.oa(a))return"function"==typeof a.item||"string"==typeof a.item;if(g.na(a))return"function"==typeof a.item}return!1};
g.ed=function(a,b,c,d){c||(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null};
g.gd=function(a,b,c,d,e,h,k){var n="";a&&(n+=a+":");c&&(n+="//",b&&(n+=b+"@"),n+=c,d&&(n+=":"+d));e&&(n+=e);h&&(n+="?"+h);k&&(n+="#"+k);return n};
g.hd=function(a){return a?(0,window.decodeURI)(a):a};
g.jd=function(a,b){return b.match(g.id)[a]||null};
g.kd=function(a){return g.hd(g.jd(3,a))};
g.ld=function(a){a=a.match(g.id);return g.gd(null,null,null,null,a[5],a[6],a[7])};
g.md=function(a){var b=a.indexOf("#");return 0>b?a:a.substr(0,b)};
g.nd=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
g.od=function(a,b,c){if(g.ha(b))for(var d=0;d<b.length;d++)g.od(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",g.va(b))};
pd=function(a,b){for(var c in b)g.od(c,b[c],a);return a};
g.qd=function(a){a=pd([],a);a[0]="";return a.join("")};
g.rd=function(a,b){return g.nd(pd([a],b))};
g.sd=function(a,b,c){a&&(c&&(c=g.Xa,c=!(c&&0<=c.toLowerCase().indexOf("cobalt"))),c?a&&(a=g.Zc("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),g.dd(a).body.appendChild(a)):zaa(a,b))};
g.td=function(a){try{window.navigator&&window.navigator.sendBeacon&&window.navigator.sendBeacon(a,"")||g.sd(a,void 0)}catch(b){g.sd(a,void 0)}};
zaa=function(a,b){var c=new window.Image,d=""+Aaa++;ud[d]=c;c.onload=c.onerror=function(){b&&ud[d]&&b();delete ud[d]};
c.src=a};
g.vd=function(a,b){this.version=a;this.args=b};
g.wd=function(a,b){this.topic=a;this.Gf=b};
g.yd=function(a,b){var c=g.xd();return c?c.publish.call(c,a.toString(),a,b):!1};
g.xd=function(){return g.m("yt.pubsub2.instance_")};
zd=function(a){g.vd.call(this,1,arguments)};
Cd=function(a){var b=a||window;if(!(b.performance&&b.performance.timing&&b.performance.getEntriesByType))return{Ei:0,lw:0};a=g.Sc(b);for(var c=[],d=b.document.getElementsByTagName("*"),e=0,h=d.length;e<h;e++){var k=d[e],n;"IMG"==k.tagName&&(n=Ad(k,k.src,a))&&c.push(n);var r=b.getComputedStyle(k)["background-image"];r&&(r=Baa.exec(r))&&1<r.length&&(n=Ad(k,r[1],a))&&c.push(n);if("IFRAME"==k.tagName)try{if(n=Bd(k,a)){var B=Cd(k.contentWindow);0<B.Ei&&(n.timing=B.Ei,c.push(n))}}catch(D){}}n=b.performance.getEntriesByType("resource");
B={};d=0;for(e=n.length;d<e;d++)h=n[d],B[h.name]=h.responseEnd;d=0;for(e=c.length;d<e;d++)h=c[d],h.timing||(h.timing=B[h.url]||0);b=Caa(b,n);a=Daa(b,a,c);h=c=0;if(a.length)for(B=n=0,d=a.length;B<d;B++)e=a[B],h=e.timing-h,0<h&&1>n&&(c+=(1-n)*h),h=e.timing,n=e.progress;return{Ei:Math.round(c||b),lw:h}};
Bd=function(a,b){if(a.getBoundingClientRect){var c=a.getBoundingClientRect(),d=Math.max(c.top,0),e=Math.min(c.right,b.width),h=Math.min(c.bottom,b.height),c=Math.max(c.left,0);if(h>d&&e>c)return new Eaa(d,e,h,c)}return null};
Ad=function(a,b,c){return b&&(a=Bd(a,c))?(a.url=b,a):null};
Caa=function(a,b){var c,d=a.performance.timing.navigationStart;if("msFirstPaint"in a.performance.timing)c=a.performance.timing.A-d;else if("chrome"in a&&"loadTimes"in a.chrome){var e=a.chrome.loadTimes(),h=e.firstPaintTime;if(0<h){var k=e.startLoadTime;"requestTime"in e&&(k=e.requestTime);h>=k&&(c=1E3*(h-k))}}if(void 0===c||0>c||12E4<c){c=a.performance.timing.responseStart-d;for(var n={},d=a.document.getElementsByTagName("head")[0].children,e=0,h=d.length;e<h;e++)k=d[e],"SCRIPT"==k.tagName&&k.src&&
!k.async?n[k.src]=!0:"LINK"==k.tagName&&"stylesheet"==k.rel&&k.href&&(n[k.href]=!0);b.some(function(a){if(!n[a.name]||"script"!=a.initiatorType&&"link"!=a.initiatorType)return!0;a=a.responseEnd;if(void 0===c||a>c)c=a})}return Math.max(c,0)||0};
Daa=function(a,b,c){for(var d={0:0},e=0,h=0,k=c.length;h<k;h++){var n=c[h],r=a;n.timing>a&&(r=n.timing);d[r]||(d[r]=0);n=(n.A-n.D)*(n.B-n.C);d[r]+=n;e+=n}h=b.width*b.height;0<h&&(h=.1*Math.max(h-e,0),a in d||(d[a]=0),d[a]+=h,e+=h);a=[];if(e){for(var B in d)b=new Faa((0,window.parseFloat)(B),d[B]),a.push(b);a.sort(function(a,b){return a.timing-b.timing});
h=d=0;for(k=a.length;h<k;h++)b=a[h],d+=b.area,b.progress=d/e}return a};
Eaa=function(a,b,c,d){this.A=c;this.C=d;this.B=b;this.D=a};
Faa=function(a,b){this.area=b;this.timing=a};
g.Hd=function(a,b,c){Dd(c)[a]=b||Ed();b||Fd(a);Gd(!1,c)};
Jd=function(a,b){Id(void 0).yt_sts=a;g.Hd("_start",b,void 0)};
Ld=function(a){Kd(a);Gaa();g.l("yt.timing.pingSent_",!1,void 0)};
Md=function(a){a=Dd(a);if(a.aft)return a.aft;for(var b=g.t("TIMING_AFT_KEYS",["ol"]),c=b.length,d=0;d<c;d++){var e=a[b[d]];if(e)return e}return window.NaN};
Od=function(a,b){var c=b||Nd(void 0).span,d;d=a.redirectEnd-a.redirectStart;0<d&&(c.rtime_=d);d=a.domainLookupEnd-a.domainLookupStart;0<d&&(c.dns_=d);d=a.connectEnd-a.connectStart;0<d&&(c.tcp_=d);d=a.connectEnd-a.secureConnectionStart;a.secureConnectionStart>=a.navigationStart&&0<d&&(c.stcp_=d);d=a.responseStart-a.requestStart;0<d&&(c.req_=d);d=a.responseEnd-a.responseStart;0<d&&(c.rcv_=d)};
Qd=function(a){return Math.round(Pd.timing.navigationStart+a)};
Haa=function(a){var b=window.location.protocol,c=Pd.getEntriesByType("resource"),d=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.googleapis.com/css?family=")})[0],c=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});
d&&0<d.startTime&&0<d.responseEnd&&(a.wfcs=Qd(d.startTime),a.wfce=Qd(d.responseEnd));c&&0<c.startTime&&0<c.responseEnd&&(a.wffs=Qd(c.startTime),a.wffe=Qd(c.responseEnd))};
Ud=function(a){var b=Dd(a),c=Nd(a).span,d=Id(a),e=g.m("yt.timing.reportbuilder_");if(e){if(e=e(b,c,d,a))Rd(e),Ld(a)}else{var h=g.t("TIMING_ACTION",void 0),k=g.t("CSI_SERVICE_NAME","youtube"),e={v:2,s:k,action:h};if(Pd.now&&Pd.timing){var n=Pd.timing.navigationStart+Pd.now(),n=Math.round((0,g.Sd)()-n);d.yt_hrd=n}var n=g.t("TIMING_INFO",{}),r;for(r in n)d[r]=n[r];r=d.srt;delete d.srt;var B;r||0===r||(B=Pd.timing||{},r=Math.max(0,B.responseStart-B.navigationStart),(0,window.isNaN)(r)&&d.pt&&(r=d.pt));
if(r||0===r)d.srt=r;d.h5jse&&(n=window.location.protocol+g.m("ytplayer.config.assets.js"),(n=Pd.getEntriesByName?Pd.getEntriesByName(n)[0]:null)?d.h5jse=Math.round(d.h5jse-n.responseEnd):delete d.h5jse);b.aft=Md(a);n=b._start;if("cold"==d.yt_lt){B||(B=Pd.timing||{});var D;a:if(D=B,D.msFirstPaint)D=Math.max(0,D.msFirstPaint);else{var N=window.chrome;if(N&&(N=N.loadTimes,g.na(N))){var N=N(),Y=1E3*Math.min(N.requestTime||window.Infinity,N.startLoadTime||window.Infinity),Y=window.Infinity===Y?0:D.navigationStart-
Y;D=Math.max(0,Math.round(1E3*N.firstPaintTime+Y)||0);break a}D=0}0<D&&D>n&&(b.fpt=D);Od(B,c);Pd.getEntriesByType&&Haa(b);(B=g.t("SPEEDINDEX_FOR_ACTIONS",void 0))&&-1<B.indexOf(h)&&(h=Ed(),B=Cd(),h=Ed()-h,0<B.Ei&&(d.si=B.Ei,b.vsc=Qd(B.lw),c.sid=h))}D=Dd(a);h=D.pbr;B=D.vc;D=D.pbs;h&&B&&D&&h<B&&B<D&&1==Id(a).yt_vis&&"youtube"==k&&(Id(a).yt_lt="hot_bg",k=b.vc,h=b.pbs,delete b.aft,c.aft=Math.round(h-k));(k=g.t("PREVIOUS_ACTION"))&&(d.pa=k);d.p=g.t("CLIENT_PROTOCOL")||"unknown";d.t=g.t("CLIENT_TRANSPORT")||
"unknown";window.navigator&&window.navigator.sendBeacon&&(d.ba=1);for(var ka in d)"_"!=ka.charAt(0)&&(e[ka]=d[ka]);b.ps=Ed();d={};ka=[];for(var ua in b)"_"!=ua.charAt(0)&&(D=Math.max(Math.round(b[ua]-n),0),d[ua]=D,ka.push(ua+"."+D));e.rt=ka.join(",");b=e;ua=[];for(var Ga in c)"_"!=Ga.charAt(0)&&ua.push(Ga+"."+Math.round(c[Ga]));b.it=ua.join(",");(Ga=g.m("ytdebug.logTiming"))&&Ga(e,d,c);Ld(a);g.t("EXP_DEFER_CSI_PING")?(Td(),g.l("yt.timing.deferredPingArgs_",e,void 0),a=g.yb(Td,0),g.l("yt.timing.deferredPingTimer_",
a,void 0)):Rd(e);g.yd(Iaa,new zd(d.aft+(r||0)))}};
Gd=function(a,b){var c=g.t("TIMING_ACTION",void 0),d=Dd(b);if(g.m("yt.timing.ready_")&&c&&d._start&&Md(b)){var c=!0,e=g.t("TIMING_WAIT",[]);if(!a&&e.length)for(var h=0,k=e.length;h<k;++h)if(!(e[h]in d)){c=!1;break}(c||b)&&Ud(b)}};
Rd=function(a){if(g.t("DEBUG_CSI_DATA")){var b=g.m("yt.timing.csiData");b||(b=[],g.l("yt.timing.csiData",b,void 0));b.push({page:window.location.href,time:new Date,args:a})}g.t("EXP_DEFER_CSI_PING")&&(g.Ab(g.m("yt.timing.deferredPingTimer_")),g.l("yt.timing.deferredPingArgs_",null,void 0));var c="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",c=g.t("CSI_LOG_WITH_YT")?"/csi_204":c,b="",d;for(d in a)b+="&"+d+"="+a[d];a=c+"?"+b.substring(1);b=g.t("DOUBLE_LOG_CSI")?
"/csi_204?"+b.substring(1):null;window.navigator&&window.navigator.sendBeacon?(g.td(a),b&&g.td(b)):(g.sd(a),b&&g.sd(b));g.l("yt.timing.pingSent_",!0,void 0)};
Td=function(a){if(g.t("EXP_DEFER_CSI_PING")){var b=g.m("yt.timing.deferredPingArgs_");b&&(a&&(b.yt_fss=a),Rd(b))}};
Dd=function(a){return Nd(a).tick};
Id=function(a){return Nd(a).info};
Nd=function(a){return g.m("ytcsi."+(a||"")+"data_")||Kd(a)};
Kd=function(a){var b={tick:{},span:{},info:{}};g.l("ytcsi."+(a||"")+"data_",b,void 0);return b};
Vd=function(a){g.m("yt.timing.pingSent_")||(g.Hd("aa"),Id(void 0).ap=1,Id(void 0).yt_fss=a,Ud())};
Jaa=function(a){a=g.Wd(a);return g.Xd(a)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};
g.Xd=function(a){return null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1};
g.Wd=function(a){a=g.kd(a);return null===a?null:a.split(".").reverse()};
g.Yd=function(a,b){g.sd("/gen_204?"+a,b)};
g.Zd=function(a){if(a.classList)return a.classList;a=a.className;return g.la(a)&&a.match(/\S+/g)||[]};
g.A=function(a,b){return a.classList?a.classList.contains(b):g.Ja(g.Zd(a),b)};
g.C=function(a,b){a.classList?a.classList.add(b):g.A(a,b)||(a.className+=0<a.className.length?" "+b:b)};
g.E=function(a,b){a.classList?a.classList.remove(b):g.A(a,b)&&(a.className=(0,g.$d)(g.Zd(a),function(a){return a!=b}).join(" "))};
g.ae=function(a,b,c){c?g.C(a,b):g.E(a,b)};
g.be=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,g.u)(a.childNodes,function(a){b.appendChild(g.be(a))}):b.innerHTML=a.innerHTML;
return b};
g.ce=function(a){this.type="";this.state=this.source=this.data=this.currentTarget=this.relatedTarget=this.target=null;this.charCode=this.keyCode=0;this.shiftKey=this.ctrlKey=this.altKey=!1;this.rotation=this.clientY=this.clientX=0;this.scale=1;this.changedTouches=this.touches=null;if(a=a||window.event){this.event=a;for(var b in a)b in Kaa||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=
b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;this.Dn=a.pageX;this.En=a.pageY}};
g.ee=function(a,b,c,d){return g.Ra(g.de,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
g.F=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=g.ee(a,b,c,d);if(e)return e;var e=++fe.count+"",h=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),k;k=h?function(d){d=new g.ce(d);if(!g.ed(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new g.ce(b);
b.currentTarget=a;return c.call(a,b)};
k=g.xb(k);g.de[e]=[a,b,c,k,d];a.addEventListener?"mouseenter"==b&&h?a.addEventListener("mouseover",k,d):"mouseleave"==b&&h?a.addEventListener("mouseout",k,d):"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style?a.addEventListener("MozMousePixelScroll",k,d):a.addEventListener(b,k,d):a.attachEvent("on"+b,k);return e};
g.ge=function(a){a=a||window.event;a.returnValue=!1;a.preventDefault&&a.preventDefault()};
g.ie=function(){if(null==g.m("_lact",window)){var a=(0,window.parseInt)(g.t("LACT"),10),a=(0,window.isFinite)(a)?(0,g.Sd)()-Math.max(a,0):-1;g.l("_lact",a,window);-1==a&&he();g.F(window.document,"keydown",he);g.F(window.document,"keyup",he);g.F(window.document,"mousedown",he);g.F(window.document,"mouseup",he);g.Lb("page-mouse",he);g.Lb("page-scroll",he);g.Lb("page-resize",he)}};
he=function(){null==g.m("_lact",window)&&(g.ie(),g.m("_lact",window));var a=(0,g.Sd)();g.l("_lact",a,window);g.v("USER_ACTIVE")};
g.je=function(){var a=g.m("_lact",window);return null==a?-1:Math.max((0,g.Sd)()-a,0)};
ke=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||g.Ua(Laa);this.assets=a.assets||{};this.attrs=a.attrs||g.Ua(Maa);this.params=a.params||g.Ua(Naa);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};
g.le=function(a){a instanceof ke||(a=new ke(a));return a};
ne=function(){return null!=g.me};
g.oe=function(){return g.me?g.me.invoke():null};
pe=function(){return(0,window.parseInt)(g.t("DCLKSTAT",0),10)};
g.qe=function(a,b,c){this.A=a;this.B=b;this.C=c};
g.re=function(a){this.A=a};
g.te=function(a){a=(a.A.cookie||"").split(g.se);for(var b=[],c=[],d,e,h=0;e=a[h];h++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
g.ve=function(a,b,c,d){g.ue.set(""+a,b,c,"/",d||"youtube.com")};
g.we=function(a,b){return g.ue.get(""+a,b)};
g.ze=function(a,b,c){var d=g.t("VALID_SESSION_TEMPDATA_DOMAINS",[]),e=g.kd(window.location.href);e&&d.push(e);e=g.kd(a);if(g.Ja(d,e)||!e&&g.ta(a,"/"))if(a=g.ld(a),a=g.md(a))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&(xe(a,b,c),ye(b))):(xe(a,b),ye(b))};
xe=function(a,b,c){var d=g.t("ST_BASE36",!0),e;e=g.t("ST_SHORT",!0)?"ST-":"s_tempdata-";a=e=d?e+g.Ca(a).toString(36):e+g.Ca(a);c=c||5;b=b?g.qd(b):"";g.ve(a,b,c)};
ye=function(a){if(a){a=a.itct||a.ved;var b=g.m("yt.logging.screenreporter.storeParentElement");a&&b&&b(new g.qe(a))}};
g.Ae=function(a,b,c){c=c||"";g.xc(window.location,g.rd(a,b||{})+c)};
g.Be=function(a,b){b&&g.ze(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):g.Ae(a)};
g.Ce=function(a,b,c){var d=g.t("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&g.ze(a,b);if(c)return!1;g.Be(a);return!0};
g.Fe=function(){return g.Wc?"Webkit":g.De?"Moz":g.z?"ms":g.Ee?"O":null};
g.Ge=function(){return g.Wc?"-webkit":g.De?"-moz":g.z?"-ms":g.Ee?"-o":null};
g.He=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
g.Ie=function(a,b){return a&&b?b instanceof g.He?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};
g.Ke=function(a,b){var c=Je[b];if(!c){var d=g.Da(b),c=d;void 0===a.style[d]&&(d=g.Fe()+g.Ea(d),void 0!==a.style[d]&&(c=d));Je[b]=c}return c};
g.Le=function(a,b){var c=a.style[g.Da(b)];return"undefined"!==typeof c?c:a.style[g.Ke(a,b)]||""};
g.Me=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};
g.Ne=function(a,b){a.style.height=g.Me(b,!0)};
g.Oe=function(a,b){a.style.width=g.Me(b,!0)};
g.Pe=function(a,b){a.style.display=b?"":"none"};
g.Re=function(){var a=g.we("PREF");if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(g.Qe[d]=c.toString())}};
Se=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};
Te=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};
g.Ue=function(a){a=void 0!==g.Qe[a]?g.Qe[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};
g.Ve=function(a,b){return!!((g.Ue("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
g.We=function(a,b){(a=g.x(a))&&a.style&&(g.Pe(a,b),g.ae(a,"hid",!b))};
g.Xe=function(a){return(a=g.x(a))?!("none"==a.style.display||g.A(a,"hid")):!1};
Oaa=function(a){if(a=g.x(a))g.Xe(a)?(g.Pe(a,!1),g.C(a,"hid")):(g.Pe(a,!0),g.E(a,"hid"))};
g.G=function(a){(0,g.u)(arguments,function(a){!g.ia(a)||a instanceof window.Element?g.We(a,!0):(0,g.u)(a,function(a){g.G(a)})})};
g.H=function(a){(0,g.u)(arguments,function(a){!g.ia(a)||a instanceof window.Element?g.We(a,!1):(0,g.u)(a,function(a){g.H(a)})})};
g.Ye=function(a){(0,g.u)(arguments,function(a){g.ia(a)?(0,g.u)(a,function(a){g.Ye(a)}):Oaa(a)})};
g.$e=function(){this.A=this.minor=this.major=0;this.C="";var a=g.m("window.navigator.plugins"),b=g.m("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,h=c.length;e<h;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.C=b;b=a;this.major=b[0];this.minor=b[1];this.A=b[2];if(0>=this.major){var k,n,r,B;if(g.Ze)try{k=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(D){k=null}else r=window.document.body,B=window.document.createElement("object"),B.setAttribute("type","application/x-shockwave-flash"),k=r.appendChild(B);if(k&&"GetVariable"in k)try{n=k.GetVariable("$version")}catch(D){n=""}r&&B&&r.removeChild(B);(k=n||
"")?(k=k.split(" ")[1].split(","),k=[(0,window.parseInt)(k[0],10)||0,(0,window.parseInt)(k[1],10)||0,(0,window.parseInt)(k[2],10)||0]):k=[0,0,0];this.major=k[0];this.minor=k[1];this.A=k[2]}};
af=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.major>b[0]||a.major==b[0]&&a.minor>b[1]||a.major==b[0]&&a.minor==b[1]&&a.A>=b[2]};
bf=function(a){return-1<a.C.indexOf("Gnash")&&-1==a.C.indexOf("AVM2")||9==a.major&&1==a.minor||9==a.major&&0==a.minor&&1==a.A?!1:9<=a.major};
Paa=function(a){return g.cf?!af(a,11,2):g.df?!af(a,11,3):!bf(a)};
ef=function(a,b,c){if(b){a=g.la(a)?g.Nc(a):a;var d=g.Ua(c.attrs);d.tabindex=0;var e=g.Ua(c.params);e.flashvars=g.qd(c.args);if(g.Ze){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var h in d)b.setAttribute(h,d[h]);for(h in e)d=window.document.createElement("param"),d.setAttribute("name",h),d.setAttribute("value",e[h]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");b.setAttribute("name",
d.id);for(h in d)b.setAttribute(h,d[h]);for(h in e)b.setAttribute(h,e[h])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};
g.hf=function(a,b){a=g.la(a)?g.Nc(a):a;b=g.le(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=g.$e.getInstance();af(c,b.minVersion)?(c=ff(b,c),ef(a,c,b)):gf(a,b,c)};
jf=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=g.le(a);var d=!!b,e=g.x(a.attrs.id),h=e?e.parentNode:null;if(e&&h){if(window!=window.top){var k=null;if(window.document.referrer){var n=window.document.referrer.substring(0,128);Jaa(n)||(k=n)}else k="unknown";k&&(d=!0,a.args.framer=k)}k=g.$e.getInstance();if(af(k,a.minVersion)){var n=ff(a,k),r="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(r=e.getAttribute("src")||e.movie);(r!=n||d)&&ef(h,n,a);Paa(k)&&Qaa()}else gf(h,a,k);c&&c()}else g.yb(function(){jf(a,
b,c)},50)}};
gf=function(a,b,c){0==c.major&&b.fallback?b.fallback():0==c.major&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+g.Fb("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};
ff=function(a,b){var c;(c=bf(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!af(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.url};
Qaa=function(){var a=g.x("flash10-promo-div"),b=g.Ve(g.Re.getInstance(),107);a&&!b&&g.G(a)};
g.kf=function(a,b){var c=a.match(Raa);window.spf.style.load(a,c?c[1]:"",b)};
g.lf=function(a){g.pb.call(this);this.A=[];this.C=a||this};
mf=function(a,b,c,d){d=g.xb((0,g.p)(d,a.C));b.addEventListener(c,d);a.A.push({target:b,name:c,Yb:d})};
nf=function(a){for(;a.A.length;){var b=a.A.pop();b.target.removeEventListener(b.name,b.Yb)}};
qf=function(a,b){g.pb.call(this);this.R=this.D=a;this.la=b;this.M=!1;this.api={};this.Xa=this.X=null;this.aa=new g.tb;g.sb(this,this.aa);this.B={};this.F=this.ab=this.C=this.tb=this.A=null;this.ga=!1;this.Y=this.G=this.O=this.V=null;this.bb={};this.mc=["onReady"];this.ia=new g.lf(this);g.sb(this,this.ia);this.Eb=null;this.Nb=window.NaN;this.qa={};of(this);this.xe("onDetailedError",(0,g.p)(this.HI,this));this.xe("onTabOrderChange",(0,g.p)(this.zy,this));this.xe("onTabAnnounce",(0,g.p)(this.op,this));
this.xe("WATCH_LATER_VIDEO_ADDED",(0,g.p)(this.LI,this));this.xe("WATCH_LATER_VIDEO_REMOVED",(0,g.p)(this.MI,this));g.pf||(this.xe("onMouseWheelCapture",(0,g.p)(this.qI,this)),this.xe("onMouseWheelRelease",(0,g.p)(this.rI,this)));this.xe("onAdAnnounce",(0,g.p)(this.op,this));this.J=new g.lf(this);g.sb(this,this.J);this.lb=!1;this.fb=null};
sf=function(a,b){a.tb=b;a.A=b.clone();a.C=a.A.attrs.id||a.C;"video-player"==a.C&&(a.C=a.la,a.A.attrs.id=a.la);a.R.id==a.C&&(a.C+="-player",a.A.attrs.id=a.C);a.A.args.enablejsapi="1";a.A.args.playerapiid=a.la;a.ab||(a.ab=rf(a,a.A.args.jsapicallback||"onYouTubePlayerReady"));a.A.args.jsapicallback=null;var c=a.A.attrs.width;c&&g.Oe(a.R,Number(c)||c);(c=a.A.attrs.height)&&g.Ne(a.R,Number(c)||c)};
tf=function(a){a.A.loaded||(a.A.loaded=!0,"0"!=a.A.args.autoplay?a.api.loadVideoByPlayerVars(a.A.args):a.api.cueVideoByPlayerVars(a.A.args))};
uf=function(a){if(!g.ca(a.A.disable.flash)){var b=a.A.disable,c;c=af(g.$e.getInstance(),a.A.minVersion);b.flash=!c}return!a.A.disable.flash};
xf=function(a){var b;if(!(b=!a.A.html5&&uf(a))){if(!g.ca(a.A.disable.html5)){var c;b=!0;void 0!=a.A.args.deviceHasDisplay&&(b=a.A.args.deviceHasDisplay);if(2.2==vf)c=!0;else{a:{var d=b;b=g.m("yt.player.utils.videoElement_");b||(b=window.document.createElement("video"),g.l("yt.player.utils.videoElement_",b,void 0));try{if(b.canPlayType)for(var d=d?Saa:Taa,e=0;e<d.length;e++)if(b.canPlayType(d[e])){c=null;break a}c="fmt.noneavailable"}catch(h){c="html5.missingapi"}}c=!c}c&&(c=wf(a)||a.A.assets.js);
a.A.disable.html5=!c;c||(a.A.args.html5_unavailable="1")}b=!!a.A.disable.html5}return b?uf(a)?"flash":"unsupported":"html5"};
Af=function(a,b){if((!b||(5!=(Uaa[b.errorCode]||5)?0:-1!=Vaa.indexOf(b.errorCode)))&&uf(a)){var c=yf(a);c&&c.stopVideo&&c.stopVideo();var d=a.A;c&&c.getUpdatedConfigurationData&&(c=c.getUpdatedConfigurationData(),d=g.le(c));d.args.autoplay=1;d.args.html5_unavailable="1";sf(a,d);zf(a,"flash")}};
zf=function(a,b){a.isDisposed()||(b||(b=xf(a)),("flash"==b?a.AO:"html5"==b?a.BO:a.CO).call(a))};
wf=function(a){var b=!0,c=yf(a);c&&a.A&&(a=a.A,b=g.w(c,"version")==a.assets.js);return b&&!!g.m("yt.player.Application.create")};
yf=function(a){var b=g.x(a.C);!b&&a.R&&a.R.querySelector&&(b=a.R.querySelector("#"+a.C));return b};
Bf=function(a,b,c){var d=b[c];return function(){try{return a.Eb=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.Eb=e,g.Cb(e,"WARNING"))}}};
of=function(a){a.M=!1;if(a.Xa)for(var b in a.B)a.Xa(b,a.B[b]);for(var c in a.qa)g.Ab((0,window.parseInt)(c,10));a.qa={};a.X=null;a.Xa=null;for(var d in a.api)a.api[d]=null;a.api.addEventListener=(0,g.p)(a.xe,a);a.api.removeEventListener=(0,g.p)(a.GM,a);a.api.destroy=(0,g.p)(a.dispose,a);a.api.getLastError=(0,g.p)(a.$z,a);a.api.getPlayerType=(0,g.p)(a.oA,a);a.api.getCurrentVideoConfig=(0,g.p)(a.zz,a);a.api.loadNewVideoConfig=(0,g.p)(a.Mo,a);a.api.isReady=(0,g.p)(a.PO,a)};
rf=function(a,b){var c=b;if("string"==typeof b){if(a.bb[b])return a.bb[b];c=function(){var a=g.m(b);a&&a.apply(g.da,arguments)};
a.bb[b]=c}return c?c:null};
Waa=function(a,b){var c="ytPlayer"+b+a.la;a.B[b]=c;g.da[c]=function(c){var e=g.yb(function(){a.isDisposed()||(a.aa.ma(b,c),g.Sa(a.qa,String(e)))},0);
g.Ta(a.qa,String(e),!0)};
return c};
Cf=function(a){return(a=yf(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
Df=function(a){g.Hd("dcp");a.cancel();of(a);a.F=null;a.A&&(a.A.loaded=!1);var b=yf(a);"html5"==Cf(a)?a.O=b:b&&b.destroy&&b.destroy();g.ad(a.D);nf(a.ia);a.G=null;a.Y=null};
g.Gf=function(a,b){a=g.la(a)?g.Nc(a):a;b=g.le(b);var c=g.Ef+"_"+g.qa(a),d=g.Ff[c];if(d)return d.Mo(b),d.api;d=new qf(a,c);g.Ff[c]=d;g.v("player-added",d.api);g.qb(d,g.ra(Xaa,d));g.yb(function(){d.Mo(b)},0);
return d.api};
Xaa=function(a){g.Ff[a.getId()]=null};
g.Hf=function(a){a=g.x(a);if(!a)return null;var b=g.Ef+"_"+g.qa(a),c=g.Ff[b];c||(c=new qf(a,b),g.Ff[b]=c);return c.api};
g.If=function(){return g.A(g.x("page-container"),"remote-connected")};
Yaa=function(){g.l("yt.abuse.botguardInitialized",ne,void 0);g.l("yt.abuse.invokeBotguard",g.oe,void 0);g.l("yt.abuse.dclkstatus.checkDclkStatus",pe,void 0);g.l("yt.player.exports.navigate",g.Ce,void 0);g.l("yt.player.embed",g.Gf,void 0);g.l("yt.player.getPlayerByElement",g.Hf,void 0);g.l("yt.util.activity.init",g.ie,void 0);g.l("yt.util.activity.getTimeSinceActive",g.je,void 0);g.l("yt.util.activity.setTimestamp",he,void 0);var a=g.m("ytplayer.config");Jf(a);g.m("ytspf.enabled")&&(Kf=g.zb(Lf,5E3),
(a=g.Mf())?(a.addEventListener("onReady",Lf),a.addEventListener("onStateChange",Lf)):Nf("unable to init PP monitor"))};
Jf=function(a){for(var b in g.Ff){var c=g.Ff[b];c&&c.cancel()}if(a=a||null){b=g.Mf();var d=!0,c=g.Of;g.Of=null;b&&b.getVideoData&&c&&(d=b.getVideoData(),d=!!c.fullscreen||d.video_id!=a.args.video_id||d.list!=a.args.list||d.video_id!=c.videoId||d.list!=c.listId);d?(Pf="",g.Gf("player-api",a)):b.playVideo();a=g.le(a);a.loaded=!0}Lf();g.l("ytplayer.config",a,void 0)};
g.Mf=function(){var a=g.m("yt.player.getPlayerByElement");return a?a("player-api"):null};
Lf=function(){var a=g.Mf();if(a){var b;b=g.x("player");b=!b||g.A(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==g.t("PAGE_NAME"),e=g.If();!c||d||e||(Nf("PP playing off watch (paused)"),a.pauseVideo());b&&d?Nf("PP off-screen on watch"):b||d||Nf("PP !off-screen off watch")}};
Nf=function(a){var b=g.t("PAGE_NAME");b&&(b=[b,Pf,g.m("_spf_state.nav-counter")],a+="("+b.join(",")+")",g.l("yt.www.persistentplayer.issue",a,void 0),g.Cb(Error(a),"WARNING"))};
Rf=function(){g.Hd("ol");g.t("CSI_TICK_PAINT_TIME")?window.requestAnimationFrame&&!window.document.hidden?window.requestAnimationFrame(function(){(0,window.setTimeout)(function(){g.Hd("cpt");Qf()},0)}):window.document.hidden?(g.Hd("cpt"),Qf()):(0,window.setTimeout)(function(){g.Hd("cpt");
Qf()},0):Qf()};
Qf=function(){Sf("init");var a=g.t("PAGE_NAME",void 0);a&&Sf("init-"+a)};
Sf=function(a){g.Ob()?Tf.push(g.Pb(g.ra(g.Nb,a),0)):g.v(a)};
Uf=function(){g.Sb(Tf);Tf.length=0;var a=g.t("PAGE_NAME",void 0);a&&g.Nb("dispose-"+a);g.Nb("dispose")};
Zaa=function(){Rf()};
$aa=function(){g.t("TIMING_REPORT_ON_UNLOAD")&&Gd(!0);Vd("u");Td("u");Uf();g.Nb("pageunload")};
aba=function(a,b,c,d,e){for(var h=window.document.getElementsByTagName("script"),k=!1,n=0,r=h.length;n<r;n++)if(0<h[n].src.indexOf("/debug-")){k=!0;break}k&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),g.Cb(e))};
Zf=function(){Vf=1;Wf=Xf=0;g.t("TIMING_REPORT_ON_UNLOAD")&&Gd(!0);Vd("n");Td("n");Ld();Jd("n");Fd("mark_navigation_requested");Yf(bba);g.Nb("navigate")};
cg=function(a){a=a.detail.part||a.detail.partial;g.Hd("nc"+Xf);++Xf;if(!a.data||!a.data.deferDispose){var b=1==Vf;Vf=2;b?(Yf(cba),$f()):Yf(dba);if(b=a.data&&a.data.swfcfg)ag(a.timing,b.args),bg(b)}};
dg=function(){g.Hd("np"+Wf);++Wf};
eg=function(a){a=a.detail.response;var b=1==Vf;Vf=3;b&&(Yf(eba),$f());if(b=a.data&&a.data.swfcfg)ag(a.timing,b.args),bg(b)};
hg=function(a){g.Hd("nd");a=a.detail.response;g.fg=a.cacheKey;a=a.timing;var b=window._spf_state,b=b&&b["nav-counter"]||0;Id(void 0).yt_nav=b;Jd("ne",a.responseStart);b=Math.max(0,a.responseStart-a.navigationStart);Id(void 0).srt=b;var c=(b=!!a.spfCached)?"hot":"warm";Id(void 0).yt_lt=c;var c=!!a.spfPrefetched,d=+c;Id(void 0).yt_pft=d;g.Hd("pfs",a.fetchStart);var d=a.responseStart,e=Nd(void 0).span,h=Dd(void 0);"pfs"in h&&(e.preq=(d||Ed())-h.pfs);"redirectStart"in a&&Od(a);Yf(gg);window.document.getElementById("content").style.height=
"";g.t("EXP_LACT_HISTORY")&&b&&!c&&he();Rf();Vf=0};
ig=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),g.Cb(a)};
jg=function(a){g.Yd(g.qd({spfreload:"1",url:a.detail.url,reason:a.detail.reason}))};
gba=function(){fba()};
hba=function(){};
$f=function(){var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");Uf();var a=g.t("TIMING_ACTION"),b;for(b in g.vb)delete g.vb[b];g.wb("PREVIOUS_ACTION",a);g.l("ytplayer.config",null,void 0);if((b=g.Mf())&&b.stopVideo){if(b.stopVideo(),b=b.getLastError())Pf=b,(b=g.x("movie_player"))&&b.stopVideo?(b.stopVideo(),Pf="recovered"):Pf="missing2"}else Pf="missing";Lf()};
bg=function(a){"cfg"in Dd(void 0)||g.Hd("cfg");Jf(a)};
Yf=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));g.Rb(kg);kg=g.Qb(function(){var c=a[0],d=a[1],e=a[2];b.className="";var h=b.style;h.transitionDuration=h.webkitTransitionDuration=c+"ms";h.width=d+"%";g.Ab(lg);lg=g.yb(function(){b.className=e},c)},0)};
fba=function(){var a=gg[0]+50;g.Ab(lg);lg=g.yb(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
ag=function(a,b){var c=a&&a.spfCached,d=a&&a.spfPrefetched,e=[];c&&!d&&(0,g.u)(iba,function(a){a in b&&(delete b[a],e.push(a))});
g.t("EXP_DEBUG_PREFETCH")&&(e.sort(),c={a:"removeNonCacheableVideoVars",cached:c,prefetched:d,deleted:e.join("")},g.Yd(g.qd(c)))};
mg=function(){g.Tb.call(this,"www/base");this.B=0};
ng=function(a){(a=a.detail.name)&&Wb(a)};
g.aa=[];g.og=g.og||{};g.da=this;pa="closure_uid_"+(1E9*Math.random()>>>0);aaa=0;g.Sd=Date.now||function(){return+new Date};g.sa[" "]=g.ea;var eaa,faa,gaa,haa,iaa,jaa,daa;g.za=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
eaa=/&/g;faa=/</g;gaa=/>/g;haa=/"/g;iaa=/'/g;jaa=/\x00/g;daa=/[\x00&<>"']/;g.pg=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
g.jba=2147483648*Math.random()|0;g.Ia=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;
if(g.la(a))return g.la(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
g.kba=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;
0>c&&(c=Math.max(0,a.length+c));if(g.la(a))return g.la(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
g.u=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.la(a)?a.split(""):a,h=0;h<d;h++)h in e&&b.call(c,e[h],h,a)};
g.$d=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],h=0,k=g.la(a)?a.split(""):a,n=0;n<d;n++)if(n in k){var r=k[n];
b.call(c,r,n,a)&&(e[h++]=r)}return e};
g.qg=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),h=g.la(a)?a.split(""):a,k=0;k<d;k++)k in h&&(e[k]=b.call(c,h[k],k,a));
return e};
g.rg=Array.prototype.reduce?function(a,b,c,d){d&&(b=(0,g.p)(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;
(0,g.u)(a,function(c,k){e=b.call(d,e,c,k,a)});
return e};
g.sg=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.la(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&b.call(c,e[h],h,a))return!0;
return!1};
g.tg=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.la(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&!b.call(c,e[h],h,a))return!1;
return!0};g.ug=g.Na(!1);g.vg=g.Na(!0);g.wg=g.Na(null);var Va="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");a:{var xg=g.da.navigator;if(xg){var yg=xg.userAgent;if(yg){g.Xa=yg;break a}}g.Xa=""};var ob;g.cb.prototype.get=function(){var a;0<this.C?(this.C--,a=this.A,this.A=a.next,a.next=null):a=this.B();return a};var kb=new g.cb(function(){return new fb},function(a){a.reset()},100);
eb.prototype.remove=function(){var a=null;this.A&&(a=this.A,this.A=this.A.next,this.A||(this.C=null),a.next=null);return a};
fb.prototype.set=function(a,b){this.Ee=a;this.scope=b;this.next=null};
fb.prototype.reset=function(){this.next=this.scope=this.Ee=null};var gb,ib=!1,jb=new eb;g.pb.prototype.Gd=!1;g.pb.prototype.isDisposed=function(){return this.Gd};
g.pb.prototype.dispose=function(){this.Gd||(this.Gd=!0,this.W())};
g.pb.prototype.W=function(){if(this.Ib)for(;this.Ib.length;)this.Ib.shift()()};g.q(g.tb,g.pb);g.f=g.tb.prototype;g.f.subscribe=function(a,b,c){var d=this.Ed[a];d||(d=this.Ed[a]=[]);var e=this.D;this.A[e]=a;this.A[e+1]=b;this.A[e+2]=c;this.D=e+3;d.push(e);return e};
g.f.unsubscribe=function(a,b,c){if(a=this.Ed[a]){var d=this.A;if(a=g.Ha(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.Fd(a)}return!1};
g.f.Fd=function(a){var b=this.A[a];if(b){var c=this.Ed[b];0!=this.B?(this.C.push(a),this.A[a+1]=g.ea):(c&&g.La(c,a),delete this.A[a],delete this.A[a+1],delete this.A[a+2])}return!!b};
g.f.ma=function(a,b){var c=this.Ed[a];if(c){for(var d=Array(arguments.length-1),e=1,h=arguments.length;e<h;e++)d[e-1]=arguments[e];if(this.F)for(e=0;e<c.length;e++){var k=c[e];maa(this.A[k+1],this.A[k+2],d)}else{this.B++;try{for(e=0,h=c.length;e<h;e++)k=c[e],this.A[k+1].apply(this.A[k+2],d)}finally{if(this.B--,0<this.C.length&&0==this.B)for(;c=this.C.pop();)this.Fd(c)}}return 0!=e}return!1};
g.f.clear=function(a){if(a){var b=this.Ed[a];b&&((0,g.u)(b,this.Fd,this),delete this.Ed[a])}else this.A.length=0,this.Ed={}};
g.f.sb=g.ba(1);g.f.W=function(){g.tb.N.W.call(this);this.clear();this.C.length=0};var Ed;g.vb=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};g.l("yt.config_",g.vb,void 0);g.l("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);g.Db=window.yt&&window.yt.msgs_||g.m("window.ytcfg.msgs")||{};g.l("yt.msgs_",g.Db,void 0);Ed=window.performance&&window.performance.timing&&window.performance.now&&window.__yt_experimental_now?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()};
g.Ze="Microsoft Internet Explorer"==window.navigator.appName;var lba=g.m("yt.pubsub.instance_")||new g.tb;g.tb.prototype.subscribe=g.tb.prototype.subscribe;g.tb.prototype.unsubscribeByKey=g.tb.prototype.Fd;g.tb.prototype.publish=g.tb.prototype.ma;g.tb.prototype.clear=g.tb.prototype.clear;g.l("yt.pubsub.instance_",lba,void 0);var Ib=g.m("yt.pubsub.subscribedKeys_")||{};g.l("yt.pubsub.subscribedKeys_",Ib,void 0);var Kb=g.m("yt.pubsub.topicToKeys_")||{};g.l("yt.pubsub.topicToKeys_",Kb,void 0);var Jb=g.m("yt.pubsub.isSynchronous_")||{};
g.l("yt.pubsub.isSynchronous_",Jb,void 0);var Hb=g.m("yt.pubsub.skipSubId_")||null;g.l("yt.pubsub.skipSubId_",Hb,void 0);g.f=g.Tb.prototype;g.f.UM=function(){this.ck()||this.init()};
g.f.enable=function(){this.A=1;(0,g.u)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.UM,this),this.subscribe("dispose-"+a,this.dispose,this),g.t("PAGE_NAME")==a&&g.Ub(this))},this)};
g.f.init=function(){g.Rb(this.C);this.A=2;this.G&&this.G()};
g.f.ck=function(){return 2==this.A};
g.f.dispose=function(){this.A=3;g.Rb(this.C);this.F&&this.F()};
g.f.disable=function(){this.A=4;this.clear();try{this.dispose()}catch(a){g.Cb(a)}};
g.f.subscribe=function(a,b,c){a=g.Lb(a,b,c);this.D.push(a);return a};
g.f.clear=function(){g.Mb(this.D);this.D=[]};var Vb=g.m("yt.modules.registry_")||{};g.l("yt.modules.registry_",Vb,void 0);var saa={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};g.mba=RegExp("[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.nba=RegExp("^[^\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.zg=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");g.Zb.prototype.Yf=!0;g.Zb.prototype.$e=function(){return this.A};
g.Zb.prototype.toString=function(){return"Const{"+this.A+"}"};
var Yb={};bc.prototype.Yf=!0;var ac={};bc.prototype.$e=function(){return this.A};
var oaa=dc(""),naa=/^([-,."'%_!# a-zA-Z0-9]+|(?:rgb|hsl)a?\([0-9.%, ]+\))$/;g.gc.prototype.Yf=!0;g.gc.prototype.$e=function(){return this.A};
g.gc.prototype.Om=!0;g.gc.prototype.Gg=function(){return 1};
var paa=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,fc={};g.ic("about:blank");g.lc.prototype.Yf=!0;g.lc.prototype.$e=function(){return this.A};
g.lc.prototype.Om=!0;g.lc.prototype.Gg=function(){return 1};
var kc={};var sc,raa,qaa,nc;g.oc.prototype.Om=!0;g.oc.prototype.Gg=function(){return this.C};
g.oc.prototype.Yf=!0;g.oc.prototype.$e=function(){return this.A};
sc=/^[a-zA-Z0-9-]+$/;raa={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};qaa={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,META:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};nc={};g.oba=g.qc("<!DOCTYPE html>",0);g.Ag=g.qc("",0);g.Bg=g.qc("<br>",0);var Ac={};var taa=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,uaa=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;g.pba=Math.sign||function(a){return 0<a?1:0>a?-1:a};g.f=g.Ec.prototype;g.f.clone=function(){return new g.Ec(this.x,this.y)};
g.f.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};
g.f.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
g.f.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.f.scale=function(a,b){var c=g.ma(b)?b:a;this.x*=a;this.y*=c;return this};g.f=g.Fc.prototype;g.f.clone=function(){return new g.Fc(this.width,this.height)};
g.f.area=function(){return this.width*this.height};
g.f.aspectRatio=function(){return this.width/this.height};
g.f.isEmpty=function(){return!this.area()};
g.f.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.f.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.f.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.f.scale=function(a,b){var c=g.ma(b)?b:a;this.width*=a;this.height*=c;return this};var Eg,Fg,Ic,Jg;g.Ee=Za();g.z=g.Ya("Trident")||g.Ya("MSIE");g.Cg=g.Ya("Edge");g.Dg=g.Cg||g.z;g.De=g.Ya("Gecko")&&!(g.xa(g.Xa.toLowerCase(),"webkit")&&!g.Ya("Edge"))&&!(g.Ya("Trident")||g.Ya("MSIE"))&&!g.Ya("Edge");g.Wc=g.xa(g.Xa.toLowerCase(),"webkit")&&!g.Ya("Edge");g.Wc&&g.Ya("Mobile");g.df=g.Ya("Macintosh");g.cf=g.Ya("Windows");g.qba=g.Ya("Linux")||g.Ya("CrOS");Eg=g.da.navigator||null;Eg&&g.xa(Eg.appVersion||"","X11");g.rba=g.Ya("Android");g.sba=g.Gc();g.tba=g.Ya("iPad");
a:{var Gg="",Hg=function(){var a=g.Xa;if(g.De)return/rv\:([^\);]+)(\)|;)/.exec(a);if(g.Cg)return/Edge\/([\d\.]+)/.exec(a);if(g.z)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(g.Wc)return/WebKit\/(\S+)/.exec(a);if(g.Ee)return/(?:Version)[ \/]?(\S+)/.exec(a)}();
Hg&&(Gg=Hg?Hg[1]:"");if(g.z){var Ig=Hc();if(null!=Ig&&Ig>(0,window.parseFloat)(Gg)){Fg=String(Ig);break a}}Fg=Gg}g.Jc=Fg;Ic={};Jg=g.da.document;g.Lc=Jg&&g.z?Hc()||("CSS1Compat"==Jg.compatMode?(0,window.parseInt)(g.Jc,10):5):void 0;var vaa;vaa=!g.z||g.Mc(9);g.uba=!g.De&&!g.z||g.z&&g.Mc(9)||g.De&&g.Kc("1.9.1");g.Kg=g.z&&!g.Kc("9");g.vba=g.z||g.Ee||g.Wc;g.wba=g.z&&!g.Mc(9);var Pc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};g.Lg="StopIteration"in g.da?g.da.StopIteration:{message:"StopIteration",stack:""};g.id=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;g.pf=g.Ya("Firefox");g.Mg=g.Gc()||g.Ya("iPod");g.Ng=g.Ya("iPad");g.xba=g.Ya("Android")&&!($a()||g.Ya("Firefox")||Za()||g.Ya("Silk"));g.Og=$a();g.Pg=g.Ya("Safari")&&!($a()||g.Ya("Coast")||Za()||g.Ya("Edge")||g.Ya("Silk")||g.Ya("Android"))&&!(g.Gc()||g.Ya("iPad")||g.Ya("iPod"));var ud={},Aaa=0,yba=g.m("yt.net.ping.workerUrl_")||null;g.l("yt.net.ping.workerUrl_",yba,void 0);g.vd.prototype.Xb=g.ba(2);g.wd.prototype.toString=function(){return this.topic};var zba=g.m("yt.pubsub2.instance_")||new g.tb;g.tb.prototype.subscribe=g.tb.prototype.subscribe;g.tb.prototype.unsubscribeByKey=g.tb.prototype.Fd;g.tb.prototype.publish=g.tb.prototype.ma;g.tb.prototype.clear=g.tb.prototype.clear;g.l("yt.pubsub2.instance_",zba,void 0);g.Qg=g.m("yt.pubsub2.subscribedKeys_")||{};g.l("yt.pubsub2.subscribedKeys_",g.Qg,void 0);g.Rg=g.m("yt.pubsub2.topicToKeys_")||{};g.l("yt.pubsub2.topicToKeys_",g.Rg,void 0);g.Sg=g.m("yt.pubsub2.isAsync_")||{};
g.l("yt.pubsub2.isAsync_",g.Sg,void 0);g.l("yt.pubsub2.skipSubKey_",null,void 0);g.q(zd,g.vd);var Iaa=new g.wd("timing-sent",zd);var Baa=/url\((http[^\)]+)\)/i;var Pd=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},Gaa=(0,g.p)(Pd.clearResourceTimings||Pd.webkitClearResourceTimings||Pd.mozClearResourceTimings||Pd.msClearResourceTimings||Pd.oClearResourceTimings||g.ea,Pd),Fd=Pd.mark?function(a){Pd.mark(a)}:g.ea;g.Aba=g.Wc?"webkit":g.De?"moz":g.z?"ms":g.Ee?"o":"";g.Tg=g.m("yt.dom.getNextId_");if(!g.Tg){g.Tg=function(){return++Bba};
g.l("yt.dom.getNextId_",g.Tg,void 0);var Bba=0};g.ce.prototype.preventDefault=function(){this.event&&(this.event.returnValue=!1,this.event.preventDefault&&this.event.preventDefault())};
g.ce.prototype.stopPropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopPropagation&&this.event.stopPropagation())};
g.ce.prototype.stopImmediatePropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopImmediatePropagation&&this.event.stopImmediatePropagation())};
var Kaa={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1,webkitMovementX:1,webkitMovementY:1};g.de=g.m("yt.events.listeners_")||{};g.l("yt.events.listeners_",g.de,void 0);var fe=g.m("yt.events.counter_")||{count:0};g.l("yt.events.counter_",fe,void 0);var Laa={enablejsapi:1},Maa={},Naa={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};ke.prototype.clone=function(){var a=new ke,b;for(b in this)if(this.hasOwnProperty(b)){var c=this[b];"object"==g.ga(c)?a[b]=g.Ua(c):a[b]=c}return a};g.me=null;g.se=/\s*;\s*/;g.f=g.re.prototype;g.f.isEnabled=function(){return window.navigator.cookieEnabled};
g.f.set=function(a,b,c,d,e,h){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');g.ca(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";h=h?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,g.Sd)()+1E3*c)).toUTCString();this.A.cookie=a+"="+b+e+d+c+h};
g.f.get=function(a,b){for(var c=a+"=",d=(this.A.cookie||"").split(g.se),e=0,h;h=d[e];e++){if(0==h.lastIndexOf(c,0))return h.substr(c.length);if(h==a)return""}return b};
g.f.remove=function(a,b,c){var d=g.ca(this.get(a));this.set(a,"",0,b,c);return d};
g.f.Rb=g.ba(3);g.f.pb=g.ba(4);g.f.isEmpty=function(){return!this.A.cookie};
g.f.sb=g.ba(0);g.f.De=g.ba(5);g.f.clear=function(){for(var a=g.te(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
g.ue=new g.re(window.document);g.ue.C=3950;g.Ug=g.z?"focusin":"DOMFocusIn";g.Cba=g.z?"focusout":"DOMFocusOut";g.Vg=g.Wc?"webkitTransitionEnd":g.Ee?"otransitionend":"transitionend";g.f=g.He.prototype;g.f.getHeight=function(){return this.bottom-this.top};
g.f.clone=function(){return new g.He(this.top,this.right,this.bottom,this.left)};
g.f.contains=function(a){return g.Ie(this,a)};
g.f.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
g.f.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
g.f.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
g.f.scale=function(a,b){var c=g.ma(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};var Je;Je={};g.Wg=g.De?"MozUserSelect":g.Wc||g.Cg?"WebkitUserSelect":null;g.fa(g.Re);g.Qe=g.m("yt.prefs.UserPrefs.prefs_")||{};g.l("yt.prefs.UserPrefs.prefs_",g.Qe,void 0);g.f=g.Re.prototype;g.f.get=function(a,b){Te(a);Se(a);var c=void 0!==g.Qe[a]?g.Qe[a].toString():null;return null!=c?c:b?b:""};
g.f.set=function(a,b){Te(a);Se(a);if(null==b)throw"ExpectedNotNull";g.Qe[a]=b.toString()};
g.f.remove=function(a){Te(a);Se(a);delete g.Qe[a]};
g.f.save=function(){var a;a=[];for(var b in g.Qe)a.push(b+"="+(0,window.escape)(g.Qe[b]));a=a.join("&");g.ve("PREF",a,63072E3)};
g.f.clear=function(){g.Qe={}};g.Xg=g.Oa(function(){if(g.z)return g.Kc("10.0");var a=window.document.createElement("DIV"),b=g.Ge(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");g.wc(a,g.uc("div",{style:c}));return""!=g.Le(a.firstChild,"transition")});g.fa(g.$e);g.$e.prototype.getVersion=function(){return[this.major,this.minor,this.A]};var Raa=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var vf;var Yg=g.Xa,Yg=Yg.toLowerCase();if(g.xa(Yg,"android")){var Zg=Yg.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(Zg)vf=Number(Zg[1]);else{var $g={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},ah=Yg.match("("+g.Qa($g).join("|")+")");vf=ah?$g[ah[0]]:0}}else vf=void 0;var Saa=['video/mp4; codecs="avc1.42001E, mp4a.40.2"','video/webm; codecs="vp8.0, vorbis"'],Taa=['audio/mp4; codecs="mp4a.40.2"'];g.q(g.lf,g.pb);g.lf.prototype.Wa=g.ba(6);g.lf.prototype.W=function(){nf(this);g.lf.N.W.call(this)};var Uaa={"api.invalidparam":2,auth:150,"drm.auth":150,heartbeat:150,"html5.unsupportedads":5,"fmt.noneavailable":5,"fmt.decode":5,"fmt.unplayable":5,"html5.missingapi":5,"drm.unavailable":5};g.q(qf,g.pb);var Vaa=["drm.unavailable","fmt.noneavailable","html5.missingapi","html5.unsupportedads","html5.unsupportedlive"];g.f=qf.prototype;g.f.getId=function(){return this.la};
g.f.Mo=function(a,b){this.isDisposed()||(sf(this,a),b||xf(this),zf(this,b),this.M&&tf(this))};
g.f.zz=function(){return this.tb};
g.f.BO=function(){if(!this.ga){var a=wf(this);a&&"html5"==Cf(this)?(this.F="html5",this.M||this.Yg()):(Df(this),this.F="html5",a&&this.O?(this.D.appendChild(this.O),this.Yg()):(this.A.loaded=!0,this.V=(0,g.p)(function(){var a=this.D,c=this.A.clone();g.m("yt.player.Application.create")(a,c);this.Yg()},this),this.ga=!0,a?this.V():(g.Cc(this.A.assets.js,this.V),g.kf(this.A.assets.css))))}};
g.f.AO=function(){var a=this.A.clone();if(!this.G){var b=yf(this);b&&(this.G=window.document.createElement("span"),this.G.tabIndex=0,mf(this.ia,this.G,"focus",this.Nt),this.Y=window.document.createElement("span"),this.Y.tabIndex=0,mf(this.ia,this.Y,"focus",this.Nt),g.bd(this.G,b),g.cd(this.Y,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==Cf(this)?(this.F="flash",this.M||jf(a,!1,(0,g.p)(this.Yg,this))):(Df(this),this.F="flash",this.A.loaded=!0,g.hf(this.D,a),
this.Yg())};
g.f.Nt=function(){yf(this).focus()};
g.f.Yg=function(){if(!this.isDisposed()){var a=yf(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(h){}if(b)if(this.ga=!1,a.isNotServable&&a.isNotServable(this.A.args.video_id))Af(this);else{of(this);this.M=!0;a=yf(this);a.addEventListener&&(this.X=Bf(this,a,"addEventListener"));a.removeEventListener&&(this.Xa=Bf(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),c=0;c<b.length;c++){var d=b[c];this.api[d]||(this.api[d]=Bf(this,
a,d))}for(var e in this.B)this.X(e,this.B[e]);tf(this);this.ab&&this.ab(this.api);this.aa.ma("onReady",this.api)}else this.Nb=g.yb((0,g.p)(this.Yg,this),50)}};
g.f.PO=function(){return this.M};
g.f.xe=function(a,b){if(!this.isDisposed()){var c=rf(this,b);if(c){if(!g.Ja(this.mc,a)&&!this.B[a]){var d=Waa(this,a);this.X&&this.X(a,d)}this.aa.subscribe(a,c);"onReady"==a&&this.M&&g.yb(g.ra(c,this.api),0)}}};
g.f.GM=function(a,b){if(!this.isDisposed()){var c=rf(this,b);c&&this.aa.unsubscribe(a,c)}};
g.f.zy=function(a){a=a?yaa:xaa;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.G||b==this.Y||(b.focus(),b!=window.document.activeElement));)b=a(b)};
g.f.op=function(a){g.v("a11y-announce",a)};
g.f.HI=function(a){Af(this,a)};
g.f.LI=function(a){g.v("WATCH_LATER_VIDEO_ADDED",a)};
g.f.MI=function(a){g.v("WATCH_LATER_VIDEO_REMOVED",a)};
g.f.qI=function(){this.lb||(g.Og?(this.fb=g.Vc(window.document),mf(this.J,window,"scroll",this.SK),mf(this.J,this.D,"touchmove",this.yK)):(mf(this.J,this.D,"mousewheel",this.$t),mf(this.J,this.D,"wheel",this.$t)),this.lb=!0)};
g.f.rI=function(){nf(this.J);this.lb=!1};
g.f.$t=function(a){g.ge(a)};
g.f.SK=function(){window.scrollTo(this.fb.x,this.fb.y)};
g.f.yK=function(a){a.preventDefault()};
g.f.CO=function(){Df(this);this.F="unsupported";var a='Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a='Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');
b=this.A.messages.player_fallback||a;a=g.x("player-unavailable");g.x("unavailable-submessage")&&a&&(g.x("unavailable-submessage").innerHTML=b,(b=g.y("icon",a))&&g.zc(b,"icon")&&(b.src=g.w(b,"icon")),g.Pe(a,!0),g.C(g.x("player"),"off-screen-trigger"))};
g.f.oA=function(){return this.F||Cf(this)};
g.f.$z=function(){return this.Eb};
g.f.cancel=function(){this.V&&g.Dc(this.A.assets.js,this.V);g.Ab(this.Nb);this.ga=!1};
g.f.W=function(){Df(this);if(this.O&&this.A)try{this.O.destroy()}catch(b){g.Cb(b)}this.bb=null;for(var a in this.B)g.da[this.B[a]]=null;this.tb=this.A=this.api=null;delete this.D;delete this.R;qf.N.W.call(this)};g.Ff={};g.Ef="player_uid_"+(1E9*Math.random()>>>0);var Dba=g.m("yt.abuse.botguardInitialized")||ne;g.l("yt.abuse.botguardInitialized",Dba,void 0);var Eba=g.m("yt.abuse.invokeBotguard")||g.oe;g.l("yt.abuse.invokeBotguard",Eba,void 0);var Fba=g.m("yt.abuse.dclkstatus.checkDclkStatus")||pe;g.l("yt.abuse.dclkstatus.checkDclkStatus",Fba,void 0);var Gba=g.m("yt.player.exports.navigate")||g.Ce;g.l("yt.player.exports.navigate",Gba,void 0);var Hba=g.m("yt.player.embed")||g.Gf;g.l("yt.player.embed",Hba,void 0);var Iba=g.m("yt.player.getPlayerByElement")||g.Hf;
g.l("yt.player.getPlayerByElement",Iba,void 0);var Jba=g.m("yt.util.activity.init")||g.ie;g.l("yt.util.activity.init",Jba,void 0);var Kba=g.m("yt.util.activity.getTimeSinceActive")||g.je;g.l("yt.util.activity.getTimeSinceActive",Kba,void 0);var Lba=g.m("yt.util.activity.setTimestamp")||he;g.l("yt.util.activity.setTimestamp",Lba,void 0);var Kf,Pf;g.Of=null;Pf="";var Tf=[];var Vf,lg,kg,Xf,Wf,iba,bba,eba,cba,dba,gg;Xf=0;Wf=0;iba=["server_prefetched_vast","vmap"];bba=[900,60,"waiting"];eba=[500,99,"waiting"];cba=[300,60,"waiting"];dba=[400,99,"waiting"];gg=[300,101,"done"];window.yt=window.yt||{};g.l("yt.setConfig",g.wb,void 0);g.l("yt.getConfig",g.t,void 0);g.l("yt.hasMsg",g.Eb,void 0);g.l("yt.pubsub.publish",g.v,void 0);g.l("yt.pubsub.subscribe",g.Lb,void 0);g.l("yt.setMsg",function(a){ub(g.Db,arguments)},void 0);
g.l("yt.setGoogMsg",function(a){ub(g.Db,arguments)},void 0);
g.l("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+Math.round(a[e]));c.rt=d.join(",");for(var h in b)"_"!=h.charAt(0)&&(c[h]=b[h]);a=g.t("TIMING_INFO",{});"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);Rd(c)},void 0);
g.l("ytcsi.tick",g.Hd,void 0);g.q(mg,g.Tb);
mg.prototype.enable=function(){window.onload=Zaa;window.onunload=$aa;window.onerror=aba;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfrequest",Zf),window.addEventListener("spfpartprocess",cg),window.addEventListener("spfpartdone",dg),window.addEventListener("spfprocess",eg),window.addEventListener("spfdone",hg),window.addEventListener("spferror",ig),window.addEventListener("spfreload",jg),window.addEventListener("spfjsbeforeunload",ng)),a.config=a.config||
{},window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",gba),this.subscribe("dispose",hba)):window.spf.dispose();
this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
mg.prototype.init=function(){mg.N.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&g.t("PAGEFRAME_JS")?(b=g.t("PAGEFRAME_JS",void 0),c=function(){window.ytPageFrameLoaded=!0;g.m("ytbin.www.pageframe.setup")()}):a&&(a=g.m("yt.www.masthead.loadSearchbox"))&&a();
var a=g.t("JS_COMMON_MODULE"),d=g.t("JS_PAGE_MODULES");d||(d=[a]);a=g.t("JS_DELAY_LOAD",0);0<a?(g.Ab(this.B),this.B=g.yb(function(){b&&g.Cc(b,c);window.spf.script.require(d)},a)):(b&&g.Cc(b,c),window.spf.script.require(d));
Yaa();g.l("yt.timing.ready_",!0,void 0);Gd(!1);var a=!!g.m("yt.reactLoaded"),e=g.t("REACT_JS",void 0);!a&&e&&g.Cc(e,function(){g.l("yt.reactLoaded",!0,void 0)})};
mg.prototype.dispose=function(){g.Ab(this.B);var a=g.m("ytbin.www.pageframe.cancelSetup");a&&a();g.Bb(Kf);if(a=g.Mf())a.removeEventListener("onReady",Lf),a.removeEventListener("onStateChange",Lf);g.l("yt.timing.ready_",!1,void 0);mg.N.dispose.call(this)};
mg.prototype.disable=function(){mg.N.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfrequest",Zf),window.removeEventListener("spfpartprocess",cg),window.removeEventListener("spfpartdone",dg),window.removeEventListener("spfprocess",eg),window.removeEventListener("spfdone",hg),window.removeEventListener("spferror",ig),window.removeEventListener("spfreload",jg),window.removeEventListener("spfjsbeforeunload",ng));window.onload=null;window.onunload=null;window.onerror=null};
g.Xb(new mg);})(_yt_www);
